kind: pipeline
type: docker
name: default 

steps:
- name: unit-testing
  image: gradle:7.5.1-jdk17
  commands:
  - cd api
  - gradle test

- name: notification-fail-unit-testing
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    username: ddvallejoj@gmail.com
    password: 
      from_secret:
        gmail_secret
    from: ddvallejoj@gmail.com
    subject: Falla en Unit Testing
    body: Se ha detectado una falla en la etapa de -unit-testing-
    recipients: 
      - dvallejo@unis.edu.gt
      - jflores@unis.edu.gt
  when:
    status:
    - failure

- name: analisis-back
  image: gradle:7.5.1-jdk17
  commands:
    - cd api
    - gradle sonar -Dsonar.qualitygate.wait=true

- name: notificacion-fail-back
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    username: ddvallejoj@gmail.com
    password: 
      from_secret:
        gmail_secret
    from: ddvallejoj@gmail.com
    subject: Falla en SonarQube Analisis BackEnd
    body: Se ha detectado una falla en la etapa de -analisis-back-
    recipients: 
      - dvallejo@unis.edu.gt
      - jflores@unis.edu.gt
  when:
    status:
    - failure

- name: analisis-front
  image: node:16.18.1
  commands:
    - npm install -g sonarqube-scanner
    - sonar-scanner #-Dsonar.qualitygate.wait=true

- name: notificacion-fail-front
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    username: ddvallejoj@gmail.com
    password: 
      from_secret:
        gmail_secret
    from: ddvallejoj@gmail.com
    subject: Falla en SonarQube Analisis FrontEnd
    body: Se ha detectado una falla en la etapa de -analisis-front-
    recipients: 
      - dvallejo@unis.edu.gt
      - jflores@unis.edu.gt
  when:
    status:
    - failure

trigger:   
  branch:
  - uat 
  event:
  - push
  - pull_request