kind: pipeline
type: docker
name: default

steps:

- name: unit-testing
  image: gradlw:7.5.1-jdk17
  commands:
  - cd api
  - ./gradlew test

#https://plugins.drone.io/plugins/sonar-plugin
#https://plugins.drone.io/plugins/sonar-node-plugin
  -name: analysis-front
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: http://sonarqube-front:9000
    sonar_token: 
      from_secret: sqp_b899ad475e92e5aaea6048a4660305754b5f886d
      # from_secret:
      # from_secret: 
      # m
      # d
      # u

- name: sonarqube-back-analysis
  image: sonarsource/sonar-scanner-cli
  environment:
    SONAR_HOST_URL: http://sonarqube:9000
  commands:
  - cd api
  - ./gradlew sonar

- name: quality-gate-back
  image: alpine
  commands:
  - timeout 1h drone wait
  - # Add logic for sending an email on failure (use Drone's notification plugin)

trigger: 
  branch:
    - main