kind: pipeline
type: docker
name: default 

steps:
# - name: unit-testing
#   image: gradle:7.5.1-jdk17
#   commands:
#   - cd api
#   - gradle test

# - name: analisis-back
#   image: gradle:7.5.1-jdk17
#   commands:
#     - cd api
#     - gradle sonar

# - name: notificacion-fail-back
#   image: drillster/drone-email
#   settings:
#     host: smtp.gmail.com
#     username: ddvallejoj@gmail.com
#     password: jtobcnjnedbqeuhi
#     from: ddvallejoj@gmail.com
#     subject: Falla en ""
#     body: Falla en ""
#     recipients: 
#       - ddvallejoj@gmail.com
#       - jflores@unis.edu.gt
#   when:
#     status:
#     - failure

- name: analisis-front
  image: kytay/sonar-node-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_main_front
    sonar_login:
      from_secret: sonar_user_token
    use_node_version: 16.18.1

- name: notificacion-fail-front
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    username: ddvallejoj@gmail.com
    password: jtobcnjnedbqeuhi
    from: ddvallejoj@gmail.com
    subject: Falla en ""
    body: Falla en ""
    recipients: 
      - ddvallejoj@gmail.com
      - jflores@unis.edu.gt
  when:
    status:
    - failure

# - name: sonarqube-back-analysis
#   image: sonarsource/sonar-scanner-cli
#   environment:
#     SONAR_HOST_URL: http://sonarqube:9000
#   commands:
#   - cd api
#   - ./gradlew sonar

# - name: quality-gate-back
#   image: alpine
#   commands:
#   - timeout 1h drone wait

trigger: 
  branch:
    - main 