name: mycelium-local-dev

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "8080:80/tcp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - mycelium-local

  api:
    image: localhost/mycelium-local_api:prod
    expose:
      - "8080"
    build:
      context: api
      dockerfile: Dockerfile.prod
    networks:
      - mycelium-local
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/api/
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=8080

  client:
    image: localhost/mycelium-local_client:prod
    expose:
      - "3000"
    build:
      context: client
      dockerfile: Dockerfile.prod
    networks:
      - mycelium-local
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000

  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    expose:
      - "1521"
    restart: always
    environment:
      ORACLE_PWD: "12345"
    volumes:
      - oracledb:/opt/oracle/oradata
    networks:
      mycelium-local:
        aliases:
          - myceliumdb

volumes:
  oracledb:

networks:
  mycelium-local:
    driver: bridge
