name: mycelium-local-dev

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "8080:80/tcp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - mycelium-local

  api:
    image: localhost/mycelium-local_api:dev
    expose:
      - "8080"
    ports:
      - "5000:8080/tcp"
    volumes:
      - ./api:/app:rw
      - gradle:/var/lib/gradle:rw
    build:
      context: api
      dockerfile: Dockerfile.dev
    networks:
      - mycelium-local
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/api/
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=8080

  api-testing:
    profiles:
      - testing
    image: localhost/mycelium-local_api:dev
    volumes:
      - ./api:/app:rw
      - gradle:/var/lib/gradle:rw
    build:
      context: api
      dockerfile: Dockerfile.dev
    entrypoint: "/app/test-entrypoint.sh"
    networks:
      - mycelium-local

  client:
    image: localhost/mycelium-local_client:dev
    expose:
      - "3000"
    volumes:
      - ./client:/app:rw
    build:
      context: client
      dockerfile: Dockerfile.dev
    networks:
      - mycelium-local
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000

  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
      - 5500:5500
    restart: unless-stopped
    environment:
      ORACLE_PWD: "12345"
    volumes:
      - oracledb:/opt/oracle/oradata
    networks:
      mycelium-local:
        aliases:
          - myceliumdb

volumes:
  oracledb:
  gradle:

networks:
  mycelium-local:
    driver: bridge
