services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Puerto 8080 para Nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    networks:
      - mycelium-local

  # api:
  #   image: localhost/mycelium-local_api:dev
  #   ports:
  #     - "8081:8080"  # Puerto 8081 para el servicio API
  #   volumes:
  #     - ./api:/app:rw
  #     - gradle:/var/lib/gradle:rw
  #   build:
  #     context: api
  #     dockerfile: Dockerfile.dev
  #   networks:
  #     - mycelium-local
  #   environment:
  #     - VIRTUAL_PATH=~^/(api|swagger|swagger-ui)
  #     - VIRTUAL_PORT=8080
  #   depends_on:
  #     - db

  client:
    image: localhost/mycelium-local_client:dev
    ports:
      - "3000:3000"  # Puerto 3000 para el cliente
    volumes:
      - ./client:/app:rw
    build:
      context: client
      dockerfile: Dockerfile.dev
    networks:
      - mycelium-local
    environment:
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000

  # db:
  #   image: container-registry.oracle.com/database/express:21.3.0-xe
  #   ports:
  #     - "1521:1521"  # Puerto 1521 para la base de datos
  #   restart: unless-stopped
  #   environment:
  #     ORACLE_PWD: "12345"
  #   volumes:
  #     - oracledb:/opt/oracle/oradata
  #   networks:
  #     - mycelium-local

  jenkins:
    image: jenkins/jenkins:lts-jdk17 
    ports:
      - "7000:8080"  # Puerto 7000 para Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - mycelium-local

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - mycelium-sonarqube
      - mycelium-local
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: Test12345
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonarqube-db:
    image: postgres
    networks:
      - mycelium-sonarqube
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=Test12345
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

#https://gist.github.com/pavankjadda/b8815276318c5f4dfaba8da2c177be5e

volumes:
  # oracledb: 
  gradle: 
  jenkins_data: 
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:

networks:
  mycelium-local:
    driver: bridge
  mycelium-sonarqube:
    driver: bridge
