micronaut:
  application:
    name: api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    reject-not-found: false
    redirect:
      enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    driverClassName: oracle.jdbc.OracleDriver
    url: "jdbc:oracle:thin:@myceliumdb:1521/XE"
    username: system
    password: "12345"
    dbType: oracle
    schemaGenerate: CREATE_DROP
    dialect: ORACLE
netty:
  default:
    allocator:
      max-order: 3
